### ISSUE TITLE
python 3.10 breaks current version of the compal library

### ISSUE THREAD

**Issue by Kiskae** [mbugert/connectbox-prometheus#6]
Tracked by https://github.com/ties/compal_CH7465LG_py/issues/25

python 3.10 (and latest security updates for the other releases) change the `parse_qs` parsing behavior which breaks the compal library. Since the docker image tracks the latest python release this means the docker build is currently broken.

A temporary fix would be to pin the docker image to `3.9.1-alpine` where it will still work until the library can be updated.

**Comment by Kiskae** [comment]
fixed in `compal 0.3.1`

**Comment by mbugert** [comment]
Hi, thanks for pointing this out.
The just released `v0.2.7` of this project now uses `compal 0.3.1`. When I built the docker image (with `FROM python:3-alpine`) it installed `python 3.8.7` so I wonder, how did you run into this issue? I manually tried with `FROM python:3.10.0a6-alpine3.13` and that worked too, so the problem is probably resolved anyway.
If it's resolved for you too, you may close this issue.

**Comment by Kiskae** [comment]
Regarding `python:3-alpine` according to [docker hub](https://hub.docker.com/_/python) that should currently be `3.9.2-alpine3.13` so it is weird that it would resolve to `3.8.7`. For me it was pulling the latest version and thus throwing an error when it tried to collect.

Regarding the `python-rc` tags it appears the change has not yet been applied to those branches (`including 3.10`). That behaviour also confused me when I [was researching the issue](https://gist.github.com/Kiskae/cb1f5cf992fa68c872c7086c2d876319#experiments).

Just tested it with a fresh docker build, it appears to be working as intended again.

**Comment by mbugert** [comment]
Solid analysis, and nice to see this library is being used :blush:. Glad it's working again for you.
